### ISSUE TITLE
Obfuscated Code

### ISSUE THREAD

**Issue by Hri7566** [LapisHusky/mppclone#117]
I was told previously by Lapis himself that the client scripts will never be obfuscated to encourage modification and to allow easy manipulation of the scripts themselves. Due to recent changes that haven't been elaborated, the client code is now obfuscated, which directly contradicts previous decisions not to do this.

**Comment by LapisHusky** [comment]
The code sent to clients is minified to improve performance, which has been the case for over a year. Anyone who opens console will see a link to this repo where the original code is public.
A stronger form of minification has recently been added using esbuild, which again is the same concept. No changes are made to the code with the intention of decreasing readability, everything is done to reduce size and improve performance.
I don't intend to remove this minification.

Actual obfuscation is done to the anti-bot code, as that is the entire purpose of the anti-bot. It is meant to be a mostly unreadable way to figure out whether someone is accessing the site in a legitimate way.
This is not a new concept, compare it to CAPTCHAs such as Cloudflare's Turnstile, Google's reCAPTCHA, or hCaptcha. All of these send code to clients which is intentionally hard to reverse-engineer, and they don't publish the source code behind them nor what is done on the server to validate.
The web does not have easy methods to identify whether someone is truly a human, as almost every existing method can be imitated by a bot just as easily. However, obfuscation does allow for better human verification, because it is significantly more effort for someone to copy and automate without failing checks.

I do not recall saying that every script sent to the client wouldn't be obfuscated (including anti-bot). I may have stated that the regular files, like script.js, client.js, and more would not be obfuscated, and I still stand by that. I intend for that part of the code to be public so people can view or modify them freely. Anything that makes those files harder to read is done with the intention of improving bandwidth usage and performance, unreadability is a side effect.

**Comment by Hri7566** [comment]
If minification to make the client load faster is our goal, why aren't all of the scripts bundled? There could be one script request instead of seven. There's a chance it might load slightly slower, but there are now 6 less requests.

**Comment by LapisHusky** [comment]
Bundling the scripts would almost certainly improve performance further. That's not implemented yet simply because nobody has done it.
